### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by mhashas** [amaiasalvador/imcap_keras#1]
I am experiencing this error when trying to train the model. Do you have any idea what's the issue and how I could fix it ? 

![screenshot from 2017-06-06 02-21-44](https://cloud.githubusercontent.com/assets/13119609/26808697/0715bd48-4a5f-11e7-85b9-1e3c67f6257e.png)

**Comment by amaiasalvador** [comment]
The error should be gone now. I was trying to get the new LSTM (the one with the sentinel gate) to generalize when the ```--sgate``` argument was not passed. I reverted this so that a regular LSTM is used in that case.

I have also made some other changes to the model. Not sure how these will impact performance though... I currently don't have much time to work on this project, but if you are using this code feel free to let me know if you find other bugs or have ideas for improvement.

Thanks !
