### ISSUE TITLE
Undeclared variables?

### ISSUE THREAD

**Issue by PavlosMelissinos** [amaiasalvador/imcap_keras#3]
Here: https://github.com/amaiasalvador/imcap_keras/blob/master/imcap/test.py#L52

lang_model is not declared and also the language_model module is never used in the file.

PS. I'm working on a similar project and I'm trying to understand how to move from training to test because during training it's necessary to feed the lstm with the word sequence, whereas during inference that's not available. What's your approach?

**Comment by amaiasalvador** [comment]
Hi, you are right. I aimed at implementing beam search assuming I would have a separate decoder ```lang_model```. I ended up not using beam search for testing so that part of the code is probably outdated. I am no longer working on this project though.

Regarding the second question, what you need to do is to set the sequence length to 1 when testing, and have a manual loop feeding the predicted word to the next timestep.

**Comment by PavlosMelissinos** [comment]
Oh, I didn't know this wasn't active anymore, sorry for bothering you.

Thanks for the response, that's really helpful :)
